### ISSUE TITLE
Deploy 1.3

### ISSUE THREAD

**Issue by capasfield** [MaastrichtU-IDS/knowledge-collaboratory-api#2]
https://arax.ncats.io/?smartapi=1 shows that Knowledge Collaboratory API has 1.2 in development (infores:knowledge-collaboratory)

Please deploy 1.3 of this tool into development ASAP.

**Comment by CaseyTa** [comment]
We've begun deploying Knowledge Collaboratory to ITRB CI and Staging as per the current schedule.

**Comment by capasfield** [comment]
Great! Thanks! I’ll add this to my notes as well.

-Carrie

Carrie Pasfield
Research Project Manager
Renaissance Computing Institute (RENCI)
University of North Carolina at Chapel Hill
***@***.***



From: Casey Ta ***@***.***>
Date: Tuesday, August 23, 2022 at 2:11 PM
To: MaastrichtU-IDS/knowledge-collaboratory-api ***@***.***>
Cc: Pasfield, Carrie Anne ***@***.***>, Author ***@***.***>
Subject: Re: [MaastrichtU-IDS/knowledge-collaboratory-api] Deploy 1.3 (Issue #2)

We've begun deploying Knowledge Collaboratory to ITRB CI and Staging as per the current schedule.

**Comment by vemonet** [comment]
Hi @capasfield we updated the TRAPI version to 1.3 in development for the Knowledge Collaboratory, thanks

**Comment by capasfield** [comment]
Fantastic! Thanks for letting me know.

-Carrie

Carrie Pasfield
Research Project Manager
Renaissance Computing Institute (RENCI)
University of North Carolina at Chapel Hill
***@***.***



From: Vincent Emonet ***@***.***>
Date: Wednesday, August 24, 2022 at 8:07 AM
To: MaastrichtU-IDS/knowledge-collaboratory-api ***@***.***>
Cc: Pasfield, Carrie Anne ***@***.***>, Mention ***@***.***>
Subject: Re: [MaastrichtU-IDS/knowledge-collaboratory-api] Deploy 1.3 (Issue #2)

Hi @capasfield<https://github.com/capasfield> we updated the TRAPI version to 1.3 in development for the Knowledge Collaboratory, thanks
